[package]
name = "dspbp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
flate2 = "*"
base64 = "*"
anyhow = "*"
thiserror = "*"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
struct_deser = "*"
struct_deser-derive = "*"
num_enum = "*"
serde_json = "*"
